using Godot;
using System;

public partial class DialogueTrigger : Area3D
{
    // Generated by Cursor: configuration for which dialogue UI to show and where.
    // Nullable with an explicit null default so it can be configured in the editor.
    [Export]
    public PackedScene? DialogueScene { get; set; } = null;

    // Generated by Cursor: per-level dialogue text that will be forwarded to the UI.
    [Export(PropertyHint.MultilineText)]
    public string DialogueText { get; set; } = string.Empty;

    // Generated by Cursor: optional NodePath to a UI root (e.g., CanvasLayer) where the dialogue UI will be added.
    // Uses the default-constructed NodePath, which is considered empty until set in the editor.
    [Export]
    public NodePath UiRootPath { get; set; } = new NodePath();

    private bool _hasTriggered;

    public override void _Ready()
    {
        // Generated by Cursor: subscribe to the Area3D body-entered signal from C#.
        BodyEntered += OnBodyEntered;
    }

    private void OnBodyEntered(Node3D body)
    {
        // Generated by Cursor: ensure the trigger only reacts once.
        if (_hasTriggered)
        {
            return;
        }

        // Require the entering body to be the player (configure the player node to be in the "Player" group).
        if (!body.IsInGroup("Player"))
        {
            return;
        }

        _hasTriggered = true;
        ShowDialogue();
    }

    private void ShowDialogue()
    {
        // Generated by Cursor: defensive checks before attempting to show dialogue.
        if (DialogueScene == null)
        {
            GD.PushWarning("DialogueTrigger: DialogueScene is not assigned. Generated by Cursor.");
            return;
        }

        var dialogueInstance = DialogueScene.Instantiate<Node>();
        if (dialogueInstance == null)
        {
            GD.PushWarning("DialogueTrigger: Failed to instantiate DialogueScene. Generated by Cursor.");
            return;
        }

        // Generated by Cursor: forward the configured text into the dialogue UI if supported.
        // The recommended pattern is for the dialogue UI script to expose:
        //  - A method named 'SetDialogueText(string text)'
        // and handle updating its internal label there.
        if (!string.IsNullOrEmpty(DialogueText))
        {
            // Prefer a dedicated method if present so we avoid relying on reflection-like APIs.
            if (dialogueInstance.HasMethod("SetDialogueText"))
            {
                dialogueInstance.Call("SetDialogueText", DialogueText);
            }
        }

        var uiRoot = ResolveUiRoot();
        if (uiRoot == null)
        {
            GD.PushWarning("DialogueTrigger: UI root not found; cannot add dialogue instance. Generated by Cursor.");
            return;
        }

        uiRoot.AddChild(dialogueInstance);

        // Optional: stop further monitoring once the dialogue has been triggered.
        Monitoring = false;
    }

    private Node? ResolveUiRoot()
    {
        // Generated by Cursor: try the explicitly assigned UI root first.
        if (!UiRootPath.IsEmpty)
        {
            var node = GetNodeOrNull(UiRootPath);
            if (node != null)
            {
                return node;
            }
        }

        // Fallback: look for a conventional UI root on the current scene (e.g., "UIRoot" or "CanvasLayer").
        var currentScene = GetTree().CurrentScene;
        if (currentScene == null)
        {
            return null;
        }

        // Try common node names without enforcing a specific structure.
        var uiRoot = currentScene.GetNodeOrNull("UIRoot")
                   ?? currentScene.GetNodeOrNull("CanvasLayer")
                   ?? currentScene.GetNodeOrNull("UI");

        return uiRoot;
    }
}
