// Generated by Github Copilot
using System;
using Godot;

public partial class Gun : Node3D
{
	[Export]
	public Node3D bulletSpawnPoint = null!;

	[Export]
	public PackedScene bulletScene = null!;

	[Export]
	public float bulletSpeed = 80.0f;

	public override void _Ready()
	{
		// Nothing to do on ready for now.
	}

	public override void _Input(InputEvent @event)
	{
		if (Input.IsActionJustPressed("fire"))
		{
			if (bulletScene == null || bulletSpawnPoint == null)
				return;

			var newBullet = bulletScene.Instantiate<RigidBody3D>();
			if (newBullet == null)
				return;

			newBullet.GlobalTransform = bulletSpawnPoint.GlobalTransform;
			var dir = -bulletSpawnPoint.Basis.X;
			newBullet.LinearVelocity = GlobalBasis * new Vector3(bulletSpeed, 0, 0);

			GetTree().CurrentScene.AddChild(newBullet);
		}
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta) { }
}
